"""Email alert — sends daily top picks via SMTP (Gmail/SMTP relay)."""
from __future__ import annotations

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import config
from bets.edge_detector import EdgeBet

logger = logging.getLogger(__name__)


class EmailAlert:
    def __init__(
        self,
        sender: str = config.EMAIL_SENDER,
        password: str = config.EMAIL_PASSWORD,
        recipient: str = config.EMAIL_RECIPIENT,
    ):
        self._sender = sender
        self._password = password
        self._recipient = recipient
        self._enabled = bool(sender and password and recipient)
        if not self._enabled:
            logger.info("Email alerts disabled — credentials not configured.")

    def _send(self, subject: str, body_html: str) -> bool:
        if not self._enabled:
            return False
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self._sender
        msg["To"] = self._recipient
        msg.attach(MIMEText(body_html, "html"))
        try:
            with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
                server.login(self._sender, self._password)
                server.sendmail(self._sender, self._recipient, msg.as_string())
            logger.info("Email sent to %s", self._recipient)
            return True
        except Exception as exc:
            logger.error("Email send failed: %s", exc)
            return False

    def send_daily_summary(self, top_bets: list[EdgeBet], bankroll: float) -> bool:
        rows = ""
        for bet in top_bets[:15]:
            rows += (
                f"<tr>"
                f"<td>{bet.sport}</td>"
                f"<td>{bet.away_team} @ {bet.home_team}</td>"
                f"<td>{bet.bet_type}</td>"
                f"<td>{bet.side.upper()}{f' {bet.line:+g}' if bet.line else ''}</td>"
                f"<td>{bet.best_odds:+.0f} ({bet.best_book})</td>"
                f"<td>{bet.model_prob:.1%}</td>"
                f"<td><b>{bet.ev_pct:+.2f}%</b></td>"
                f"<td>${bet.recommended_stake:.2f}</td>"
                f"</tr>"
            )

        html = f"""
        <html><body>
        <h2>Sports Betting Model — Daily Picks</h2>
        <p>Bankroll: <strong>${bankroll:,.2f}</strong></p>
        <table border="1" cellpadding="4" cellspacing="0">
          <thead>
            <tr>
              <th>Sport</th><th>Game</th><th>Type</th><th>Side</th>
              <th>Odds (Book)</th><th>Model Prob</th><th>EV %</th><th>Stake</th>
            </tr>
          </thead>
          <tbody>{rows}</tbody>
        </table>
        <p><em>Generated by sports-betting-model</em></p>
        </body></html>
        """
        return self._send("Sports Betting Model — Daily Picks", html)
